---
  collectd: # where your collectd server is
    host: "localhost"
    port: 25826
    interval: 10000 # in ms
  rfxcom: # usb port where rfxtrx433 is connected. May work also with rfxlan. see https://github.com/bigkevmcd/node-rfxcom
    usb: "/dev/ttyUSB1"
  probes: # description of each probe where we want to retrieve values. Currently only Oregon Temp/Humidity probes are retrieved. Very easy to add new type. see rfxcon_collectd.coffee file and https://github.com/bigkevmcd/node-rfxcom to see how to do
    one:
      name: "Probe one"
      id: "0x1234" # as seen in "debug mode" (comment out all console.log line and add ", debug: true" in RfxCom initialization in rfxcon_collectd.coffee file
      type: "oregon-th"
      channel: 1
    two:
      name: "Probe two"
      id: "0x5678"
      type: "oregon-th"
      channel: 2
